try :

    def additoin(x, y):
          x = 10
          y = 20
          print("Addition:", x + y)


    additoin(10, 20)

    print ("the operation is successful")

except NameError :

    print (" There are a error in Name ")

except :
    
    print (" There are a error ")
  

